config/routes.rb
Nois3lab::Application.routes.draw do
  resources :discounts

  resources :taxes

  resources :companies

  resources :items

  resources :invoices do
    match 'send' => 'invoices#send'
    match 'issue' => 'invoices#issue'
    match 'undo' => 'invoices#credit'
  end

  devise_for :users

  match '/works/sync' => 'works#sync'

  match '/add_item' => 'items#create'
  match '/remove_item/:id' => 'invoices#remove_item'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/tags/:id' => 'tags#list'

  mount Ckeditor::Engine => "/ckeditor"

  resources :event_details

  resources :job_positions

  resources :skills

  resources :works do
    resources :tags
  end

  resources :tags

  resources :services

  resources :media_assets

  get "home/index"
  get "about/index"

  resources :posts

  resources :teammates

  resources :clients

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  root :to => 'home#index'
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :description, :doc_id, :invoice_id, :client_id, :name, :discount_id, :tax_id
  belongs_to :client
  has_many :items, :dependent => :destroy
  has_many :taxes

  DRAFT = :draft
  PENDING = :pending
  ISSUED = :issued
  SENT = :sent
  RETIRED = :retired

  validates :name, :presence => true
  validates :client_id, :presence => true

  def invoice_number
    return 'FT-' + invoice_id.to_s + '-' + year.to_s
  end

  def credit_number
    return 'NC-' + invoice_id.to_s + '-' + year.to_s
  end

  def clients
    clients = Client.find(:all)
  end

  def discounts
    discounts = Discount.find(:all)
  end

  def taxes
    taxes = Taxis.find(:all)
  end

  def subtotal
    ret = 0
    items = Item.find_all_by_invoice_id(invoice_id)
    #logger.info items
    items.each do |t|
      ret += t.total
    end
    return ret
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end


  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @company = Company.first
    @invoice = Invoice.find(params[:id])
    @invoice.client = Client.find(@invoice.client_id)
    @items = Item.find_all_by_invoice_id(@invoice.invoice_id)
    # @invoice.tax_value = Taxis.find(:all, :conditions => { :id => @invoice.tax_id })
    # tax_value = @invoice.tax.value
    #@tax_amount = @invoice.subtotal * (1 - @tax.value/100)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
      format.pdf do
        render :pdf => "file_name"
      end
    end
  end

  def issue
    @counter = InvoiceNumbers.first
    if @counter.year != Date.today.year
      @counter.year = Date.today.year
      @counter.number = 0
    end
    @counter.number += 1
    @counter.save!
    @invoice.status = Invoice::ISSUED
    @invoice.save!
  end

  def credit
    @company = Company.first
    @invoice = Invoice.find(params[:id])
    @invoice.client = Client.find(@invoice.client_id)
    @items = Item.find_all_by_invoice_id(@invoice.invoice_id)
    @counter = InvoiceNumbers.first
    if @counter.year != Date.today.year
      @counter.year = Date.today.year
      @counter.number = 0
    end
    @counter.number += 1
    @counter.save!
    @invoice.year = @counter.year
    @invoice.invoice_id = @counter.number
    @invoice.status = Invoice::RETIRED
    # @invoice.tax_value = Taxis.find(:all, :conditions => { :id => @invoice.tax_id })
    # tax_value = @invoice.tax.value
    #@tax_amount = @invoice.subtotal * (1 - @tax.value/100)
    respond_to do |format|
      format.html # credit.html.erb
      format.json { render json: @invoice }
      format.pdf do
        render :pdf => "file_name"
      end
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new
    @counter = InvoiceNumbers.first
    @items = Item.find_all_by_invoice_id(@invoice.invoice_id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
    @counter = InvoiceNumbers.first
    @items = Item.find_all_by_invoice_id(@invoice.invoice_id)
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(params[:invoice])
    @invoice.client_id = params[:clients]
    @invoice.discount_id = params[:discount_id]
    @invoice.tax_id = params[:tax_id]
    @invoice.status = Invoice::DRAFT
    @invoice.year = @counter.year
    @invoice.invoice_id = @counter.number
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def issue
    @invoice = Invoice.find(params[:invoice_id])
    @invoice.status = Invoice::ISSUED
    @counter = InvoiceNumbers.first
    if @counter.year != Date.today.year
      @counter.year = Date.today.year
      @counter.number = 0
    end
    @counter.number += 1
    @counter.save!
    @invoice.year = @counter.year
    @invoice.invoice_id = @counter.number

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])
    @invoice.year = Date.today.year

    @invoice.client_id = params[:clients]
    @invoice.discount_id = params[:discount_id]
    @invoice.tax_id = params[:tax_id]


    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  def remove_item
    @item = Item.find(params[:id])
    @item.destroy
  end


end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fied">
    <h3 id="invoice_id" class="hidden"><%= @counter.number %></h3>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :doc_id %><br />
    <%= f.number_field :doc_id %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
    <%= select_tag "clients", options_from_collection_for_select(@invoice.clients, "id", "name", @invoice.client_id),  :prompt => "Select something" %>
  </div>
  <table class="items">
    <tr>
      <th>name</th>
      <th>quantity</th>
      <th>unit price</th>
      <th>total price</th>
      <th></th>
    </tr>
    <% @items.each do |t| %>
        <tr class="item">
          <td>
            <%= text_field_tag 'name', nil, :disabled => true, :placeholder => 'Insert your item name', :value => t.name,  :class=> 'changeable' %>
          </td>
          <td>
            <%= select_tag "count", "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option>".html_safe, :disabled => true, :class=> 'changeable' %>
          </td>
          <td>
            <%= text_field_tag 'unit_price', nil, :disabled => true, :placeholder => 'Unit price', :value => t.unit_price, :size => 6, :class => 'unit_price changeable' %>
          </td>

          <td class="total">
            <span><%= @invoice.subtotal %></span> €
          </td>
          <td>
            <a href="#" class="edit_item">edit</a>
            <a href="#" class="remove_item" id="item_<%= t.id %>">remove</a>
          </td>
        </tr>
    <% end %>
    <%= render "shared/item_row" %>
  </table>
  <div class="field">

  </div>
  <div class="field">

  </div>
  <div class="field">
    <h4 id="subtotal">subtotal <span><%= @invoice.subtotal %></span> €</h4>
    <div class="field">discount <%= f.collection_select :discount_id, @invoice.discounts, :id, :value %> %</div>
    <h3 id="total"></h3>
    <div class="field">tax amount <%= f.collection_select :tax_id, @invoice.taxes, :id, :value %> %</div>
    <h3 id="grand_total"></h3>
  </div>
  <div class="actions">
    <%= f.submit :class=> 'button'%>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice <%= @invoice.invoice_number %> <span class="status">(<%= @invoice.status %>)</span></h1>

<div class="field actions">
  <%= link_to 'ISSUE', invoice_issue_path(@invoice.id) %> | <%= link_to 'RETIRE', invoice_issue_path(@invoice.id) %>
</div>
<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <tr>
    <th>Invoice N.</th>
    <th>Name</th>
    <th>Description</th>
    <th>Total</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoices.each do |invoice| %>
  <tr>
    <td><%= invoice.invoice_number %></td>
    <td><%= invoice.name %></td>
    <td><%= invoice.description %></td>
    <td><%= invoice.subtotal %></td>
    <td><%= invoice.status %></td>
    <td><%= link_to 'Show', invoice %></td>
    <td><%= link_to 'Edit', edit_invoice_path(invoice)%></td>
    <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "issue a credit note", :controller => "invoices", :action => "credit", :format => 'pdf' %>

<%= @company.name %>
<p>
  <b>N:</b>
  <%= @invoice.invoice_number %>
</p>
<p>
  <b>Name:</b>
  <%= @invoice.name %>
</p>


<p>
  <b>Description:</b>
  <%= @invoice.description.html_safe %>
</p>

<p>
  <b>Doc:</b>
  <%= @invoice.doc_id %>
</p>

<p>
  <b>Client:</b>
  <%= @invoice.client.name %>
</p>

<table>

  <% @invoice.items.each do |t| %>
    <tr>
      <td><%=t.name %></td>
      <td><%=t.quantity.to_s %></td>
      <td><%=t.unit_price.to_s %> €</td>
    </tr>
  <% end %>

</table>
<p>
  <b>subtotal: <%= @invoice.subtotal %></b>
</p>

<%= link_to "Printable Invoice (PDF)", invoice_path(@invoice, :format => 'pdf') %>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>